name: CI

on:
  release:
    types: [ published ]

env:
  CHART_NAME: "empty-chart"
  CHART_DIR: "./charts/empty-chart"
  OCI_URL: "oci://ghcr.io/leonbrandt/"
  VERSION: ${{ github.event.release.tag_name }}
  OCI_TARGET: "${{ env.OCI_URL }}${{ env.CHART_NAME }}:${{ env.VERSION }}"

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Helm
        uses: azure/setup-helm@v4
        id: install
        with:
          version: "latest"

      - name: Log into ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lint Helm
        id: lint
        run: helm lint $CHART_DIR

      - name: Package Helm
        id: package
        run: |
          helm package $CHART_DIR --version $VERSION
          echo "package=$CHART_NAME-$VERSION.tgz" >> "$GITHUB_OUTPUT"

      - name: Push Helm
        id: push
        run: helm push $PACKAGE $OCI_TARGET
        env:
          PACKAGE: ${{ steps.package.outputs.package }}

