name: CI

on: [push]

env:
  CHART_DIR: "./empty-chart"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Helm
        uses: azure/setup-helm@v4.2.0
        id: install
        with:
          version: "latest"

      - name: Lint Helm
        run: helm lint $CHART_DIR

