name: CI

on: [push]

env:
  CHART_DIR: "./charts/empty-chart"

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Helm
        uses: azure/setup-helm@v4.2.0
        id: install
        with:
          version: "latest"

      - name: Lint Helm
        run: helm lint $CHART_DIR

      - name: Release
        uses: helm/chart-releaser-action@v1.6.0
        with:
          skip_existing: true
          # mark_as_latest: false
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

