name: CI

on: [ push ]

env:
  CHART_NAME: "empty-chart"
  CHART_DIR: "./charts/${{ CHART_NAME }}"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Helm
        uses: azure/setup-helm@v4
        id: install
        with:
          version: "latest"

      - name: Lint Helm
        id: lint
        run: helm lint $CHART_DIR

